### ISSUE TITLE
Source Coder

### ISSUE THREAD

**Issue by shoaib-intro** [charles-typ/DeepLog-introduction#1]
Hi,
I readout your complete paper is one of the best research you've done.
I am trying this in my research work as pre-task and looking for source code but unale to find source code which includes three models features:

1. `logKey` based prediction of next key (= log key path stacked LSTM based prediction)
2. `log Parameter` based prediction of next parameter (= log parameters LSTM based prediction)
3. `Workflow` clustering based creation.

I have looked around different repos with name '`deeplog`' and wasted a long time on learning repos but nowhere found complete three models implementation. I looked into following repos:
```
https://github.com/donglee-afar/logdeep
https://github.com/Wapiti08/DeepLog
https://github.com/wuyifan18/DeepLog
https://github.com/nailo2c/deeplog
https://github.com/PragyaShukla2580/DeepLog
```

could you please provide any source to get done as part of pre-work in my research. 

email: m.shoaib_ali@outlook.com

Best Regards,

**Comment by charles-typ** [comment]
Hey,

As I mentioned in the [README](https://github.com/charles-typ/DeepLog-introduction/blob/master/README.md). this repo is just for sharing slides to help learn Deeplog.

I'm not an author of the paper and never implemented this before, please consider directly reaching out to the paper authors for the code.
